// <auto-generated />
namespace GestionFlux.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixsendtouserinrequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixsendtouserinrequest));
        
        string IMigrationMetadata.Id
        {
            get { return "202205151045556_fix send-to-user in request"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
